from datetime import datetime

from .user import User


class Notification:
    counter = 1

    def __init__(self, type: str, message: str, receiver: User):
        self.__notification_id = (
            Notification.counter
        )  # Auto generated by system every time a notification is created
        self.__type = type  # What type of notification is this, can be removed
        self.__message = message  # The main box of the message
        self.__generated_date = datetime.now()  # Generated date is the current time
        self.__is_read = False  # Notifications come as unread by default
        Notification.counter = Notification.counter + 1

    def markAsRead(self):
        self.__is_read = True
        print("The notification has been marked as read.")
        pass

    def display(self):
        print(self.__message)
        pass

    def sendTo(self, userid):
        pass
