from datetime import date, datetime, timedelta

from .user import User


class Notification:
    counter = 1

    def __init__(self, type: str, message: str):
        self.__notification_id = (
            Notification.counter
        )  # Auto generated by system every time a notification is created
        self.__type = type  # What type of notification is this
        self.__message = message  # The main box of the message
        self.__generated_date = datetime.now()  # Generated date is the current time
        self.__is_read = False  # Notifications come as unread by default
        Notification.counter = Notification.counter + 1

    def markAsRead(self):
        self.__is_read = True
        return "The notification has been marked as read."

    def getInfo(self):
        status = "Read" if self.__is_read else "Not read"
        return (
            f"---Notification---\n"
            f"Id      : {self.__notification_id}\n"
            f"Type    : {self.__type}\n"
            f"Message : {self.__message}\n"
            f"Date    : {self.__generated_date}\n"
            f"Status  : {status}\n"
        )

    @staticmethod
    def remindDeadline(deadline: date, task_title: str):
        remaining_time = deadline - date.today()
        days_left = remaining_time.days
        if timedelta(0) < remaining_time <= timedelta(days=3):
            return f"{task_title} is due in {days_left} days."
